INSERT INTO INVOICES(ID, BUSINESS_ID, DOCUMENT_DATE, SOLD_DATE, PAYMENT_DATE, PAYMENT_KIND)
    VALUES (1, '2015/09/03', '2015-10-01', '2015-10-02', '2015-10-16', 'TWO_WEEKS');

INSERT INTO INVOICE_ITEMS(ID, INVOICE_ID, QUANTITY, COMMODITY, AUXILIARY_SYMBOL, MEASURE, SINGLE_NET_PRICE, TAX_RATE, ITEM_RECORD_NUMBER)
    VALUES (1, 1, 1, 'Pruning trees', 'SWW/PKWIU/1', 'item', 1499.99, 5, 0);

INSERT INTO INVOICE_ITEMS(ID, INVOICE_ID, QUANTITY, COMMODITY, AUXILIARY_SYMBOL, MEASURE, SINGLE_NET_PRICE, TAX_RATE, ITEM_RECORD_NUMBER)
    VALUES (2, 1, 2, 'Mowing', 'SWW/PKWIU/2', 'item', 499.99, 7, 1);

INSERT INTO INVOICE_PURCHASERS(ID, INVOICE_ID, NAME, ADDRESS, TAX_ID, ROLE, PURCHASER_RECORD_NUMBER)
    VALUES (1, 1, 'John Doe Inc.', 'Spitfire Street 12, London', '1234567890', 'Purchaser', 0);
